data:
  raw_data_paths:  # List of paths to raw transaction data files
    - data/raw/transactions_1.csv
    - data/raw/transactions_2.csv
  processed_data_dir: "data/processed"  # Directory to save preprocessed data
  train_test_split:
    train_year: 2019
    train_month: 1

preprocessing:
  monthly_data:
    periodic_col: "year_month"
    fill_value: 0

  feature_engineering:
    monthly:
      min_lag: 1
      max_lag: 13
      window: 1
      fill_value: 0.0
    tri_monthly:
      min_lag: 3
      max_lag: 13
      window: 3
      fill_value: 0.0

  rolling_window:
    window_size: 3